pool:
  name: MyLocalAgentPool

stages:
  - stage:
    displayName: WelcomeJob
    jobs:
    - job: Job1
      steps:
      - script: echo "Hello World"
        displayName: ExecutingScript
  - stage:
    displayName: BuildJob
    jobs:
    - job:
      displayName: StartBuild
    - job:
      displayName: RunningBuild
    - job:
      displayName: BuildCompleted
  - stage:
    displayName: CopyJob
